using libMotdepasse;
Console.WriteLine("Saisir votre login");
string login=Console.ReadLine();
Console.WriteLine("Saisir votre mot de passe");
string password=Console.ReadLine();
Motdepasse conn = new Motdepasse(login, password);
Console.WriteLine("Resaissiez votre mot de passe");
string mdp=Console.ReadLine();
Console.WriteLine(conn.Verifier(mdp));
Console.WriteLine(conn.Longueur());
Console.WriteLine(conn.EstNumeric());
Console.WriteLine(conn.EstMajuscule());
Console.WriteLine(conn.EstSpecial());
Console.WriteLine("Saisir votre login");
string lol = Console.ReadLine();
Console.WriteLine("Saisir votre mot de passe");
string pass = Console.ReadLine();
Console.WriteLine(lol);
Motdepasse tutu = new Motdepasse(lol, pass);
Console.WriteLine(tutu.Verifier(mdp));
